; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_flags =
    -std=c++17
build_unflags =
    -std=gnu++11
lib_deps =
    rodrigodornelles/TonePitch@^1.0.3

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
build_flags =
    ${env.build_flags}
lib_deps =
    ${env.lib_deps}
lib_ignore =
    HAL_Sim

[env:Simulator]
platform = native
build_flags =
    ${env.build_flags}
    -DSIMULATOR=1
    -I${platformio.libdeps_dir}/${PIOENV}/TonePitch/src
    -DDEBUG
    -O0
    -Og
    -lportaudio
lib_deps =
    ${env.lib_deps}
    https://github.com/PortAudio/portaudio#v19.7.0
lib_ignore =
    HAL_Atmel
    portaudio
